apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    monitor-annotation: full service monitor
  labels:
    app.kubernetes.io/component: cicd-sample
    app.kubernetes.io/instance: docs
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: cicd-sample
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/version: 1.0.0
    exordis/application: cicd-sample
    exordis/application-instance: docs
    exordis/application-type: service
    exordis/environment: test
    exordis/product: Some Product
    exordis/subsystem: cicd
    helm.sh/chart: cicd-subsystem-application-0.1.0
    monitor-labels: full service monitor
  name: cicd-sample-docs-full
  namespace: cicd-test
spec:
  endpoints:
    - interval: 10s
      path: /extra-metrics
      port: api
    - interval: 30s
      port: metrics
      relabelings:
        - action: labeldrop
          regex: pod
  jobLabel: full-service
  namespaceSelector:
    matchNames:
      - cicd-test
  selector:
    matchLabels:
      exordis/application: cicd-sample
      exordis/application-instance: docs
      exordis/environment: test
      exordis/subsystem: cicd
