apiVersion: v2
name: cicd-subsystem-application
description: Base helm-chart for deployment of application as a part of subsystem
type: application
version: 0.1.0
annotations:
  sdk.engine.templates-prefix: subsystem-application
dependencies:
  - name: cicd-sdk
    alias: sdk
    version: "~0.1.28"
    repository: oci://registry.gitlab.com/knst/cy/registry/charts
    # version: "0.1.0"
    # repository: file://../helm-chart-cicd-sdk 
