application: ""
applicationType: service
instanceName: ""
replicas: 3
# version: 0.0.0
applicationContainer: {}
envs: {}

global:
#  product: 
#  subsystem: 
#  environment:
  naming:
    secret: "{{.subsystem}}-{{.application}}-{{.id}}"
    config-map: "{{.subsystem}}-{{.application}}-{{.id}}"
