{{- include "sdk.engine.init" $ -}}
{{- range  $.entities.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
data:
  {{- .data  | toYaml | nindent 2 }}
binaryData:  
  {{- .binaryData  | toYaml | nindent 2 }}
{{- end -}}