{{- include "sdk.engine.init" $ -}}
{{- range  $.entities.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
  schedule: {{ .schedule | quote}}
  concurrencyPolicy: "{{ .concurrencyPolicy }}"
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit}}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "subsystem-application.metadata.common-labels" $ | nindent 12 }}
          annotations:
            {{- include "subsystem-application.metadata.common-annotations" $ | nindent 12 }}      
        spec: 
          serviceAccountName: {{ .serviceAccountName | quote}}
          restartPolicy: {{ .restartPolicy }}
          containers: 
            {{- range .containers }}
            - {{  .spec | toYaml |  nindent 14 | trim }}
            {{- end }}      
          initContainers:
            {{- range .initContainers }}
            - {{ .spec | toYaml | nindent 14 | trim }}
            {{- end }}
          volumes:
            {{- range .volumes }}
            - name: {{ .name }}
              {{ .type }}: {{ .spec | toYaml | nindent 16 }}
            {{- end }}                
{{- end -}}