{{- include "sdk.engine.init" $ -}}
{{- range  $.entities.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
  {{- /* store spec and metadata from template and parent keys*/ -}}
  {{- $jobTemplate := .spec.jobTemplate | default dict  -}}
  {{- $jobTemplate_spec := $jobTemplate.spec | default dict  -}}
  {{- $template_spec := dig "template" "spec" dict $jobTemplate_spec  -}}
  {{- $template_metadata := dig "template" "metadata" dict $jobTemplate_spec  -}}
  {{- /* unset keys to be output last*/ -}}
  {{- $_ := unset .spec "jobTemplate"  -}}
  {{- $_ := unset $jobTemplate "spec"  -}}
  {{- $_ := unset $jobTemplate_spec "template"  -}}
  {{- /* extend template metadata with common metadata*/ -}}
  {{- $_ := set $template_metadata "labels" (mustMergeOverwrite ($template_metadata.labels | default dict) (include "subsystem-application.metadata.common-labels" $ | fromYaml) ) -}}
  {{ .spec | toYaml | nindent 2 }}
  jobTemplate: 
    {{ if $jobTemplate}}{{ $jobTemplate | toYaml | nindent 4 }}{{ end }}
    spec: 
      {{ if $jobTemplate_spec}}{{ $jobTemplate_spec | toYaml | nindent 6 }}{{ end }}
      template:
        metadata:
          {{ $template_metadata | toYaml | nindent 10 }}
        spec: 
          containers: 
            {{- range .containers }}
            - {{  .spec | toYaml |  nindent 14 | trim }}
            {{- end }}      
          initContainers:
            {{- range .initContainers }}
            - {{ .spec | toYaml | nindent 14 | trim }}
            {{- end }}
          volumes:
            {{- range .volumes }}
            - {{ .spec | toYaml | nindent 14 }}
            {{ end }}                
          {{ if $template_spec}}{{ $template_spec | toYaml | nindent 10 }}{{ end }}
{{- end -}}