{{- include "sdk.engine.init" $ -}}
{{- $namespace := include "sdk.naming.subsystem.namespace" (list $.Values.global.subsystem  $.Values.global.environment) -}}
{{- range  $.entities.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
  replicas: {{ $.Values.replicas }}
  revisionHistoryLimit: {{ $.Values.deployment.revisionHistoryLimit | default 2}}
  selector:
    matchLabels:
      {{- (include "subsystem-application.metadata.selector-labels" $) | nindent 6 }}
  strategy: 
    {{- $.Values.deployment.strategy | toYaml | nindent 4}}
  template:
    metadata:
      labels:
        {{- include "subsystem-application.metadata.common-labels" $ | nindent 8 }}
      annotations:
        {{- range $configMap := $.entities.configMaps -}}    
          {{- if  $configMap.namespace | eq $namespace }}    
        checksum/configMap.{{$configMap.id}}: {{ include "sdk.common.checksum" (list $configMap.data) }}
          {{- end }}
        {{- end }}
        {{- range $secret := $.entities.secrets -}}
          {{- if  $secret.namespace | eq $namespace }}   
        checksum/secret.{{$secret.id}}: {{ include "sdk.common.checksum" (list $secret.stringData) }}
          {{ end -}}
        {{- end }}          
    spec:
      containers: 
        {{- range .containers }}
        - {{  .spec | toYaml |  nindent 10 | trim }}
        {{- end }}
      initContainers:
        {{- range .initContainers }}
        - {{ .spec | toYaml | nindent 10 | trim }}
        {{- end }}
      volumes:
        {{- range .volumes }}
        - name: {{ .name }}
          {{ .type }}: {{ .spec | toYaml | nindent 12 }}
        {{- end }}
{{- end }}

