{{- include "sdk.engine.init" $ -}}
{{- $namespace := include "sdk.naming.subsystem.namespace" (list $.Values.global.subsystem  $.Values.global.environment) -}}
{{- if $.Values.deployment -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdk.naming.application.deployment" (list $.Values.global.subsystem $.Values.application $.Values.instanceName) }}
  namespace: {{ $namespace |quote }}
  labels:
    {{- include "subsystem-application.metadata.common-labels" $ | nindent 4 }}
  annotations:
    {{- include "subsystem-application.metadata.common-annotations" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      {{- (include "subsystem-application.metadata.selector-labels" $) | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "subsystem-application.metadata.common-labels" $ | nindent 8 }}
      annotations:
        {{- range $configMap := $.entities.configMaps -}}    
          {{- if  $configMap.namespace | eq $namespace }}    
        checksum/configMap.{{$configMap.id}}: {{ include "sdk.common.checksum" (list $configMap.data) }}
          {{- end }}
        {{- end }}
        {{- range $secret := $.entities.secrets -}}
          {{- if  $secret.namespace | eq $namespace }}   
        checksum/secret.{{$secret.id}}: {{ include "sdk.common.checksum" (list $secret.stringData) }}
          {{ end -}}
        {{- end }}          
    spec:
      containers:
{{- range $.entities.containers -}}
  {{- if .parent | not }}
        - {{ .spec | toYaml |  nindent 10 | trim }}
  {{- end -}}
{{- end }}
      initContainers:
{{- range $.entities.initContainers -}}
  {{- if .parent | not }}
        - {{ .spec | toYaml | nindent 10 | trim }}
  {{- end -}}
{{- end }}
      volumes:
{{- range $.entities.volumes }}
  {{- if .parent | not }}
        - name: {{ .name }}
          {{ .type }}: {{ .spec | toYaml | nindent 12 }}
  {{- end -}}
{{- end }}

{{- end }}

