{{- include "sdk.engine.init" $ -}}
{{- range  $.entities.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
  {{ .spec | toYaml | nindent 2 }}
  template:
    metadata:
      labels:
        {{- include "subsystem-application.metadata.common-labels" $ | nindent 8 }}
      annotations:
        {{- range $configMapId := .referencedConfigMaps }}
        checksum/configMap.{{$configMapId}}: {{ include "sdk.common.checksum" (list (get $.entities.configMaps $configMapId).data ) }}
        {{- end -}}
        {{- range $secretId := .referencedSecrets }}
        checksum/secret.{{$secretId}}: {{ include "sdk.common.checksum" (list (get $.entities.secrets $secretId).stringData ) }}
        {{- end }}
    spec:
      containers: 
        {{- range .containers }}
        - {{  .spec | toYaml |  nindent 10 | trim }}
        {{- end }}
      initContainers:
        {{- range .initContainers }}
        - {{ .spec | toYaml | nindent 10 | trim }}
        {{- end }}
      volumes:
        {{- range .volumes }}
        - {{ .spec | toYaml | nindent 10 | trim }}
        {{- end }}
{{- end }}

