{{- include "sdk.engine.init" $ -}}
{{- range $.entities.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
  {{- .spec | toYaml | nindent 2  -}}

{{- end -}}
