{{- include "sdk.engine.init" $ -}}
{{ range $.entities.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ include "sdk.naming.subsystem.namespace" (list $.Values.global.subsystem  $.Values.global.environment) }}
  labels:
    {{- include "subsystem-application.metadata.common-labels" $ | nindent 4 }}
  annotations:
    {{- include "subsystem-application.metadata.common-annotations" $ | nindent 4 }}
    {{- if .useTls }}
    cert-manager.io/cluster-issuer: {{ $.Values.certManagerClusterIssuer }}
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: {{ .useRegex | quote }}
    {{ if .rewriteTarget }}nginx.ingress.kubernetes.io/rewrite-target: {{.rewriteTarget}}{{ end }}
spec:
  {{- .spec | toYaml | nindent 2  }}
{{- end -}}
