{{- include "sdk.engine.init" $ -}}
{{ range $.entities.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
  {{- .spec | toYaml | nindent 2  }}
{{- end -}}
