{{- include "sdk.engine.init" $ -}}
{{- range $.entities.pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "subsystem-application.metadata.common-labels" $ | nindent 4 }}
  annotations:
    {{- include "subsystem-application.metadata.common-annotations" $ | nindent 4 }}
spec:
{{ .spec | toYaml | indent 2 }}

{{- end -}}
