{{- include "sdk.engine.init" $ -}}
{{- /* TODO: check for flag indicating if template should be created or pvc must be a pvc */ -}}
{{- range $.entities.pvcs -}}
{{- if $.Values.workload.kind | ne "StatefulSet" | or (not .convertToTemplateForStatefulSet) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
{{ .spec | toYaml | indent 2 }}

{{- end -}}
{{- end -}}
