{{- include "sdk.engine.init" $ -}}
{{- range $.entities.secrets }}
---
apiVersion: v1
kind: Secret
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
type: {{ .type }}
data:
  {{- .data  | toYaml | nindent 2 }}
stringData:
  {{- .stringData  | toYaml | nindent 2 }}

{{- end -}}
