{{- include "sdk.engine.init" $ -}}
{{- range  $.entities.services }}
---
apiVersion: v1
kind: Service
metadata:  {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
{{ .spec | toYaml | indent 2 }}

{{- end }}
