{{- include "sdk.engine.init" $ -}}
{{- range $.entities.serviceAccounts }}
---
{{- $metadata := include "subsystem-application.metadata.entity-metadata" (list $ .) | fromYaml -}}
apiVersion: v1
kind: ServiceAccount
metadata: {{ $metadata | toYaml | nindent 2}}
{{- range $clusterRole := .clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {{ $metadata | toYaml | nindent 2}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $clusterRole | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $metadata.name }}
    namespace: {{ $metadata.namespace }}
{{- end }}
{{- end -}}

