{{- include "sdk.engine.init" $ -}}
{{- range $.entities.serviceMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}
  namespace: {{ include "sdk.naming.subsystem.namespace" (list $.Values.global.subsystem  $.Values.global.environment) }}
  labels:
    {{- include "subsystem-application.metadata.common-labels" $ | nindent 4 }}
  annotations: 
    {{- include "subsystem-application.metadata.common-annotations" $ | nindent 4 }}    
spec:
{{ .spec | toYaml | indent 2 }}
{{- end -}}

