{{- include "sdk.engine.init" $ -}}
{{- range $.entities.serviceMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
{{ .spec | toYaml | indent 2 }}
{{- end -}}

