{{- include "sdk.engine.init" $ -}}
{{- range  $.entities.statefulsets }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ .) | nindent 2}}
spec:
  {{- /* store spec and metadata from template*/ -}}
  {{- $template_spec := dig "template" "spec" dict .spec  -}}
  {{- $template_metadata := dig "template" "metadata" dict .spec  -}}
  {{- /* unset template*/ -}}
  {{- $_ := unset .spec "template"  -}}
  {{- /* extend template metadata with common metadata*/ -}}
  {{- $_ := set $template_metadata "labels" (mustMergeOverwrite ($template_metadata.labels | default dict) (include "subsystem-application.metadata.common-labels" $ | fromYaml) ) -}}
  {{- /* extend template metadata with checksum annotations for configmaps*/ -}}
  {{- $_ := set $template_metadata "annotations" ($template_metadata.annotations | default dict) -}}
  {{- range $configMapId := .referencedConfigMaps }}
    {{- $_ := set $template_metadata.annotations (printf "checksum/configMap.%s" $configMapId) (include "sdk.common.checksum" (list (get $.entities.configMaps $configMapId).data )) -}}
  {{- end -}}
  {{- /* extend template metadata with checksum annotations for secrets*/ -}}
  {{- range $secretId := .referencedSecrets }}
    {{- $_ := set $template_metadata.annotations (printf "checksum/secret.%s" $secretId) (include "sdk.common.checksum" (list (get $.entities.secrets $secretId).stringData )) -}}
  {{- end }}  
  {{ .spec | toYaml | nindent 2 }}
  template:
    spec:
      containers: 
        {{- range .containers }}
        - {{  .spec | toYaml |  nindent 10 | trim }}
        {{- end }}
      initContainers:
        {{- include "subsystem-application.helpers.sort-init-container" (list $ .) | nindent 8 }}
      volumes:
        {{- range .volumes }}
          {{- if hasKey . "volumeClaimTemplate" | not }}
        - {{ .spec | toYaml | nindent 10 | trim }}
          {{- end }}
        {{- end }}
      {{ if $template_spec}}{{ $template_spec | toYaml | nindent 6 }}{{ end }}
    metadata:
      {{ $template_metadata | toYaml | nindent 6 }}
  volumeClaimTemplates:
    {{- /* TODO: check for flag indicating if template should be created or pvc must be a pvc */ -}}
    {{- range .pvcs }}
    - apiVersion: v1	
      kind: PersistentVolumeClaim
      metadata: {{ include "subsystem-application.metadata.entity-metadata" (list $ . true true) | nindent 8 }}
      spec: {{ .spec | toYaml | nindent 8   }}
    {{- end }}
    
{{- end }}

