$schema: https://json-schema.org/draft-07/schema#
definitions:
  ingressBackend:
    type: object
    additionalProperties: false
    properties:
      service:
        type: string
        pattern: ^[a-z]([-a-z0-9]*[a-z0-9])?$
      port:
        type: integer
      foreign:
        type: boolean
    required:
      - port
      - service