$schema: https://json-schema.org/draft-07/schema#
type: object
additionalProperties: false
properties:
  type:
    type: string
    enum:
      - public
      - internal
  default_backend:
    $ref: "ingress-backend.yaml"
  rewriteTarget:
    type: string
  proxyBodySize:
    type: integer
  proxyBuffering:
    type: boolean
  useRegex:
    type: boolean
  useTls:
    type: boolean
  hosts:
    type: array
    items:
      type: string
  annotations:
    type: object
    patternProperties:
      ^.+$:
        type: string
  paths:
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        path:
          type: string
        pathType:
          type: string
        backend:
          $ref: "ingress-backend.yaml"
      required:
        - path
  spec:
    type: object
  # test:
  #   $ref: "#/definitions/ingress-backend1"
required:
  - hosts
  - paths
# definitions:
#   ingress-backend1:
#     $ref: "ingress-backend.yaml"