apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: cicd-sample
    app.kubernetes.io/instance: docs
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: cicd-sample
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/version: 1.0.0
    exordis/application: cicd-sample
    exordis/application-instance: docs
    exordis/application-type: service
    exordis/environment: test
    exordis/product: Some Product
    exordis/subsystem: cicd
    helm.sh/chart: cicd-subsystem-application-0.1.0
  name: cicd-sample-docs-gitlab-token
  namespace: cicd-test
spec:
  data:
    - remoteRef:
        key: GITLAB_PYPI_REGISTRY_LOGIN
      secretKey: login
    - remoteRef:
        key: GITLAB_PYPI_REGISTRY_PASSWORD
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cicd-test
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cicd-sample-docs-gitlab-token
    template:
      data:
        GITLAB_PYPI_REGISTRY_LOGIN: '{{ `{{ .login }}` }}'
        GITLAB_PYPI_REGISTRY_PASSWORD: '{{ `{{ .password }}` }}'
      engineVersion: v2
      metadata:
        annotations: null
        labels:
          app.kubernetes.io/component: cicd-sample
          app.kubernetes.io/instance: docs
          app.kubernetes.io/managed-by: helm
          app.kubernetes.io/name: cicd-sample
          app.kubernetes.io/part-of: cicd
          app.kubernetes.io/version: 1.0.0
          exordis/application: cicd-sample
          exordis/application-instance: docs
          exordis/application-type: service
          exordis/environment: test
          exordis/product: Some Product
          exordis/subsystem: cicd
          helm.sh/chart: cicd-subsystem-application-0.1.0
