services:
  # Full Service Definition
  full: # service id
    annotations: 
      service-annotation: "full service definition"
    labels: 
      service-label: "full service definition"
    spec: # service spec (spec.ports, spec.selector are ignored)
      type: LoadBalancer
    ports:
      api:
        port: 8080 # service port number
        targetPort: http # container port name
        protocol: TCP # default TCP
        monitorEndpoint: # item for spec.endpoints of service monitor
          interval: 10s   
          path: /extra-metrics     
      metrics:
        port: 81 # service port number
        targetPort: 80 # reference port by number instead of name
        protocol: TCP # default TCP
        monitorEndpoint: # item for spec.endpoints of service monitor
          interval: 30s
          relabelings:
            - action: labeldrop
              regex: pod          
    monitor:
      annotations: 
        monitor-annotation: "full service monitor"
      labels: 
        monitor-labels: "full service monitor"
      spec: 
        jobLabel: full-service # job label for collected metrics