envs: 
  TEST: 123
  SUBSYSTEM: wrong-subsystem

#TODO: replace with dict name->spec
volumes:
  volume1:
    #spec:
    #type: emptyDir
    mounts: 
      application: /some-data
      jsreport: /some-another-data-but-same-as-for-application

dataFolders:
  content:
    "templates":
      spec:
        imagePullPolicy: Always
      image:
        # registry: "templates"
        version: 1.24.0-dev.5
        repository: "software-development/subsystems/some-subsystem/data-content-templates"
      sizeLimit: 200Mi
      mounts: #shouldn't be empty
        application:
          "/data/templates/original": null #use key by default or /data/templates/original
          "/data/templates/generated": /data/templates/generated
        jsreport:
          "/data/templates/generated": /jsreport
        



        
